<? $this->pageTitle = "Please Login";
$this->additionalScripts = '
    <script src="/assets/js/script.js"></script>
'; 
?>
<div id="content">
    <div id="left-column" class="left">
        <div id="logo">
            <img src="/assets/img/logo-home.png" alt="BuzzyGals Logo" />
        </div>
    </div>
    <div id="right-column" class="right">
        <div id="login_option">
            <input type="button" id="login_option_button" value="Login" />
            <p>
                Don't have an account? <a href="user/signup">Signup</a>
            </p>
        </div>
        <div id="login" style="display: none">
            <?
            if (is_array($this -> error)) {
                echo '<div id="login_errors">';
                foreach ($this->error as $error) {
                    echo '<p class="red">' . $error . '</p>';
                }
                echo '</div>';
            }
            ?>
            <form action="/user/login" method="post" id="login_form">
                <input type="text" name="username" id="login_username" placeholder="Username"/>
                <input type="password" name="password" id="login_password" placeholder="Password"/>
                <input type="submit" name="submit" value="Login"/>
                <input type="checkbox" name="keepLoggedIn" value="keepLoggedIn" />
                <span class="red" id="loggedin">Keep me logged in</span>
            </form>
        </div>
    </div>
    <div class="clearfix"></div>
</div>

