<?php

/**
 * Model_Base_Userstory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property timestamp $date
 * @property string $content
 * @property integer $user
 * @property Model_User $User
 * @property Doctrine_Collection $Userstorycomment
 * 
 * @package    ElleFab
 * @subpackage Data Access Layer
 * @author     Royalty Club - Jarrod Placide-Raymond <royaltyclubvp@royalty-club.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Userstory extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('userstory');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('date', 'timestamp', null, array(
             'type' => 'timestamp',
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('user', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_User as User', array(
             'local' => 'user',
             'foreign' => 'id'));
        $this->hasOne('Model_Profile as Profile', array(
            'local' => 'user',
            'foreign' => 'user'
        ));
        $this->hasMany('Model_Userstorycomment as Comments', array(
             'local' => 'id',
             'foreign' => 'story'));
        $this->hasOne('Model_Userstorymedia as Media', array(
             'local' => 'id',
             'foreign' => 'userStory'));
    }
}