<?php
$this->additionalBodyClasses = 'townhall';
$this->additionalScripts = '<script src="/assets/js/articles.js"></script>';
?>

<div id="sidebar">
    <div id="icon">
        <img src="/assets/img/townhall-large.png" alt="<? echo $this->menuTitle ?> Townhall"/>
    </div>
    <div id="townhall_search">
        <form action="/townhalls/search" method="get">
            <input type="text" name="search" placeholder="Search Articles / Resources"/>
        </form>
    </div>
</div>
<div id="articles" data-bind="with: article">
    <article class="single_page_article" data-bind="attr: { 'id': domID }">
        <div id="title_image">
            <img data-bind="attr: { 'src': titleImageUrl, 'alt': title }" width="460" height="215"/>
        </div>
        <header>
            <h1 class="left" data-bind="text: title"></h1>
            <aside class="right" id="date" data-bind="text: date"></aside>
            <div class="clearfix"></div>
            <h2 class="left author" data-bind="text: authorName"></h2>
            <div class="right button">
                <span data-bind="visible: bookmarked()==0, click: bookmark">Bookmark Article</span>
                <span data-bind="visible: bookmarked()==1, click: removebookmark">Remove Bookmark</span>    
            </div>
            <div class="clearfix"></div>
        </header>
        <div id="article_content">
            <p data-bind="html: content"></p>
        </div>
        <div id="comments" data-bind="visible: comments().length > 0">
            <div class="count" data-bind="click: showComments">Show <span data-bind="text: commentCount()"></span> <span data-bind="text: commentText"></span></div>
            <div class="inner-comment-container" data-bind="visible: commentsVisible()==1, foreach: comments">
                <div class="comment">
                    <div class="left username" data-bind="text: displayName"></div>
                    <time class="right date" data-bind="attr: { 'datetime': date }"></time>
                    <div class="clearfix"></div>
                    <img data-bind="attr: { 'src': userPhoto, 'alt': displayName }" width="35" height="30"/>
                    <div class="comment_content"><p data-bind="text: content"></p></div>
                    <div class="clearfix"></div>
                </div>
            </div>         
        </div>
        <textarea class="add_comment expanding" data-bind="expandingTextarea: true, hasfocus: showAddCommentButton, value: newComment"></textarea>
        <input name="addcomment" type="button" class="submit_button"  value="Post" data-bind="visible: showAddCommentButton()==true || newComment().length > 0, click: addComment"/>
    </article>
</div>
<? $this->variablesJS = '<script type="text/javascript">
    var articleImagesUrl="'.Zend_Registry::get("articleImagesUrl").'";
    var profileImagesUrl="'.Zend_Registry::get('profileImagesUrl').'";
    var article='.Zend_Json::encode($this->article).';
    var bookmarked="'.$this->bookmarked.'";
</script>';
echo $this->variablesJS; ?>
