<? echo $this->doctype() ?> <!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
    <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

        <title>BuzzyGals.com - <? echo $this->pageTitle ?></title>
        <meta name="description" content="">

        <meta name="viewport" content="width=device-width">

        <? echo $this->headLink()->prependStylesheet('/assets/css/style.css') ?>
        <? echo $this->headScript()->prependFile('/assets/js/libs/modernizr-2.5.3.min.js') ?>
    </head>
    <body id="single">
        <header id="body_header">
            <div id="welcome">
                <img src="/assets/img/welcometoellefab.png" alt="Welcome to BuzzyGals"/>
            </div>
        </header>
        <div id="main" role="main">
            <? echo $this->layout()->content ?>
        </div>
        <footer id="body_footer">
            <nav>
                <ul>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Terms</a></li>
                    <li><a href="#">Privacy</a></li>
                    <li><a href="#">Advertisers</a></li>
                </ul>
            </nav>
            <div id="copyright">
                &copy; 2012 BuzzyGals
            </div>
        </footer>
        <script src="/assets/js/libs/jquery-1.7.2.min.js"></script>
        <script src="/assets/js/script.js"></script>
    </body>
</html>