<?php

/**
 * Model_ArticlecommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_ArticlecommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_ArticlecommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Articlecomment');
    }
}