<?php

/**
 * Model_FeaturedarticlesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_FeaturedarticlesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_FeaturedarticlesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Featuredarticles');
    }
}