<?php

/**
 * Model_FeaturedAuthorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_FeaturedAuthorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_FeaturedAuthorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_FeaturedAuthor');
    }
}