<?php

/**
 * Model_FollowedarticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_FollowedarticleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_FollowedarticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Followedarticle');
    }
}