<?php

/**
 * Model_FriendrequestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_FriendrequestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_FriendrequestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Friendrequest');
    }
}