<?php

/**
 * Model_FriendshipTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_FriendshipTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_FriendshipTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Friendship');
    }
}