<?php

/**
 * Model_MessagesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_MessagesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_MessagesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Messages');
    }
}