<?php

/**
 * Model_ProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_ProfileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_ProfileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Profile');
    }
}