<?php

/**
 * Model_RecipientTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_RecipientTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_RecipientTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Recipient');
    }
}