<?php

/**
 * Model_ResourceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_ResourceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_ResourceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Resource');
    }
}