<?php

/**
 * Model_ResourcetypesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_ResourcetypesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_ResourcetypesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Resourcetypes');
    }
}