<?php

/**
 * Model_ResourcetopicTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_ResourcetopicTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_ResourcetopicTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Resourcetopic');
    }
}