<?php

/**
 * Model_SessionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_SessionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_SessionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Session');
    }
}