<?php

/**
 * Model_TopicTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_TopicTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_TopicTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Topic');
    }
}