<?php

/**
 * Model_User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ElleFab
 * @subpackage Data Access Layer
 * @author     Royalty Club - Jarrod Placide-Raymond <royaltyclubvp@royalty-club.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_User extends Model_Base_User
{
    protected $_hashing = null;
    
    public function setPassword($password) {
        if($this->_hashing == NULL) $this->_hashing = new Cryptography_HashingService();
        return $this->_set('password', $this->_hashing->Compute($password));
    }
    
    public function setUp() {
        parent::setUp();
        $this->hasMany('Model_Topic as TopicsFollowed', array(
            'local' => 'user',
            'foreign' => 'topic',
            'refClass' => 'Model_Followedtopic'
        ));
        $this->hasMany('Model_Featuredarticles as ArticlesFollowed', array(
            'local' => 'user',
            'foreign' => 'article',
            'refClass' => 'Model_Followedarticle'
        ));
    }
}