<?php

/**
 * Model_UserstoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_UserstoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_UserstoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Userstory');
    }
}