<?php

/**
 * Model_UsergroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_UsergroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_UsergroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Usergroup');
    }
}