<?php

/**
 * Model_UserstorycommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_UserstorycommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_UserstorycommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Userstorycomment');
    }
}