<?php
$this -> menuTitle = 'My Profile';
$this -> additionalBodyClasses = 'my_profile';
$this -> additionalScripts = '
    <script src="/assets/js/jquery.imgareaselect-0.3.min.js"></script>
    <script src="/assets/js/uploader/header.js"></script>
    <script src="/assets/js/uploader/util.js"></script>
    <script src="/assets/js/uploader/button.js"></script>
    <script src="/assets/js/uploader/handler.base.js"></script>
    <script src="/assets/js/uploader/handler.form.js"></script>
    <script src="/assets/js/uploader/handler.xhr.js"></script>
    <script src="/assets/js/uploader/uploader.basic.js"></script>
    <script src="/assets/js/uploader/uploader.js"></script>
    <script src="/assets/js/uploader/jquery-plugin.js"></script>
    <script src="/assets/js/profile.js"></script>';
$this->profileImagesUrl = Zend_Registry::get('profileImagesUrl');
$this->userGalleryImagesUrl = Zend_Registry::get('userGalleryImagesUrl');
$this->userGalleryThumbsUrl = Zend_Registry::get('userGalleryThumbsUrl');
$this -> profileLocation = '';
if ($this -> profile['Location']['city'] != '')
    $this -> profileLocation .= $this -> profile['Location']['city'] . ', ';
if ($this -> profile['Location']['stateprov'] != '')
    $this -> profileLocation .= $this -> profile['Location']['stateprov'] . ', ';
if ($this -> profile['Location']['country'] != '')
    $this -> profileLocation .= $this -> profile['Location']['country'];
?>
<div id="photo">
    <div id="profile_photo">
        <img src="<? echo $this->profileImagesUrl.$this->profile['photo'] ?>" alt="Profile Image - <? echo $this->profile['displayName'] ?> height="250" width="200" />
        <input type="button" class="submit_button change_photo" value="Change Photo" data-bind="click: $root.showProfileUpload, visible: $root.profileUploadVisible()==0"/>
    </div>
    <div class="change_profile_photo" data-bind="visible: $root.profileUploadVisible()==1">
        <div class="profile_upload_container unstyled" data-bind="profileUploader: true"></div>
    </div>
    <div id="display_name">
        <h2><? echo $this->profile['displayName'] ?></h2>
    </div>
    <div id="location">
        <p><? echo $this->profileLocation ?></p>
    </div>
</div>
<div id="profile_content">
    <div id="profile_menu">
        <ul data-bind="foreach: pages">
            <li data-bind="text: $data, css: { selected: $data.replace(/\s/g, '') == $root.currentPage() }, click: $root.goToPage"></li>
        </ul>
        <div class="clearfix"></div>
    </div>
    <div id="profile_page">
        <div data-bind="template: { name: 'about-template', if: currentPage() == 'AboutMe' }"></div>
        <div data-bind="template: { name: 'townhalls-template', if: currentPage() == 'MyTownhalls' }"></div>
        <div data-bind="template: { name: 'friends-template', if: currentPage() == 'Friends' }"></div>
        <div data-bind="template: { name: 'stories-template', if: currentPage() == 'MyStories'}"></div>
        <div data-bind="template: { name: 'resources-template', if: currentPage() == 'MyResources' }"></div>
        <div data-bind="template: { name: 'new-story-template', if: currentPage() == 'NewStory' }"></div>
        <div data-bind="template: { name: 'crop-profile-image-template', if: currentPage() == 'CropProfileImage' }"></div>
        
        <!-- Templates -->
        
        <!-- ABOUT -->
        <script type="text/html" id="about-template">
            <div class="profile_section_title" id="aboutme">
                <div class="left section_title">About Me</div>
                <div class="right section_button" data-bind="click: $root.showAboutEdit">Edit</div>
                <div class="clearfix"></div>
            </div>
            <div class="profile_section_content" data-bind="with: profile">
                <div class="editbox" data-bind="visible: $root.aboutEdit">
                    <textarea class="profile_edit expanding" data-bind="value: about" placeholder="Tell Us About Yourself"></textarea>
                    <input name="save_about" type="button" class="submit_button"  value="Save" data-bind="click: $root.saveAbout"/>
                </div>
                <p data-bind="text: about, visible: $root.aboutEdit() == false"></p>
            </div>
            <div class="profile_section_title" id="interests">
                <div class="left section_title">My Interests</div>
                <div class="right section_button" data-bind="click: $root.showInterestsEdit">Edit</div>
                <div class="clearfix"></div>
            </div>
            <div class="profile_section_content" data-bind="with: profile">
                <div class="editbox" data-bind="visible: $root.interestsEdit">
                    <textarea class="profile_edit expanding" data-bind="value: interests" placeholder="Tell Us About Your Interests"></textarea>
                    <input name="save_interests" type="button" class="submit_button"  value="Save" data-bind="click: $root.saveInterests"/>
                </div>
                <p data-bind="text: interests, visible: $root.interestsEdit() == false"></p>
            </div>
        </script>
        
        <!-- TOWNHALLS -->
        <script type="text/html" id="townhalls-template">
            <div class="profile_section_title" id="mytownhalls">
                <div class="left section_title">My Townhalls</div>
                <div class="clearfix"></div>
            </div>
            <div class="profile_section_content">
                <div id="townhall_list" data-bind="foreach: townhalls">
                    <div class="single_townhall">
                        <a data-bind="attr: { 'href': url }">
                            <img src="/assets/img/townhall-large.png" width="90" height="93"/>
                        </a>
                        <h2 data-bind="text: title"></h2>
                    </div>
                </div>
            </div>
            <div class="profile_section_title" id="bookmarkedarticles">
                <div class="left section_title">Bookmarked Articles</div>
                <div class="clearfix"></div>
            </div>
            <div class="profile_section_content">
                <div id="bookmark_list" data-bind="foreach: bookmarkedArticles">
                    <article>
                        <div class="left bookmark_title" ><a data-bind="attr: { 'href': url }, text: title"></a></div>
                        <div class="right section_button remove_bookmark_button" data-bind="click: $root.removeBookmark">Remove Bookmark</div>
                        <div class="clearfix"></div>
                         <div class="left bookmark_topic" data-bind="text: topic"></div>
                         <div class="right section_button share_button">Share</div>
                        <div class="clearfix"></div>
                    </article>
                </div>
            </div>
        </script>
        
        <!-- FRIENDS -->
        <script type="text/html" id="friends-template">
            <div class="profile_section_title" id="myfriends">
                <div class="left section_title">My Friends</div>
                <div class="clearfix"></div>
            </div>
            <div class="profile_section_content" data-bind="foreach: friends">
                <div class="friend left">
                    <a data-bind="attr: { 'href': url }">
                        <img data-bind="attr: { 'src': photo }" alt="Friend Image" class="left" width="62" height="62"/>
                    </a>
                    <div class="info right">
                        <div class="username" data-bind="text: displayName"></div>
                        <div class="location" data-bind="text: location"></div>
                        <div class="message">
                            <a data-bind="click: $root.sendNewMessage">
                                <img src="/assets/img/msg-icon-red.png" alt="Send Message"/>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </script>
       
        <!-- STORIES -->
       	<script type="text/html" id="stories-template">
           <div class="profile_section_title" id="mystories">
                <div class="left section_title">My Stories</div>
                <div class="right section_button" data-bind="click: $root.addNewStory">New Story</div>
                <div class="clearfix"></div>
           </div>
           <div class="profile_section_content" data-bind="foreach: stories">
               <article class="story">
                    <aside class="details">
                        <time class="date" data-bind="attr: { 'datetime': date }"></time>
                    </aside>              
                    <!-- Photo Gallery -->
                    <section class="photogallery" data-bind="if: galleryAvailable">
                        <!-- Preview Photos -->
                        <div class="preview" data-bind="foreach: previewPhotos">
                            <a class="thumb modal" data-bind="attr: { 'rel': $parent.id , 'href': full }, galleryModal: true">
                                <img data-bind="attr: { 'src': thumbnail }" alt="" width="140" height="140" />
                            </a>
                        </div>
                        <!-- Main Gallery -->
                        <div class="main_gallery" data-bind="foreach: mainPhotos, visible: galleryVisible()==1">
                            <a class="thumb modal" data-bind="attr: { 'rel': $parent.id , 'href': full }, galleryModal: true">
                                <img data-bind="attr: { 'src': thumbnail }" alt="" width="140" height="140" />
                            </a>
                        </div>
                        <span class="photo_total"><span data-bind="text: photocount"></span> Photos</span>
                        <div data-bind="visible: photocount > 3">
                            <span class="more_photos" data-bind="visible: galleryVisible()==0, click: toggleGallery">Show Full Gallery</span>
                            <span class="more_photos" data-bind="visible: galleryVisible()==1, click: toggleGallery">Hide Full Gallery</span>
                        </div>
                        <span class="clearfix"></span>
                    </section>
                    <!-- Story -->
                    <section class="story_body">
                        <span class="preview" data-bind="html: contentPreview"></span><span data-bind="visible: fullStoryVisible()==0 && contentFull.length > 0">...</span>
                        <span class="main_story_body" data-bind="html: contentFull, visible: fullStoryVisible()==1"></span>
                        <div data-bind="visible: contentFull.length > 0">
                            <span class="option_more" data-bind="visible: fullStoryVisible()==0, click: toggleFullStory">Show All</span>
                            <span class="option_more" data-bind="visible: fullStoryVisible()==1, click: toggleFullStory">Hide</span>
                        </div>
                        <div class="clearfix"></div>
                    </section>
                    <!-- Comments-->
                    <section class="comments" data-bind="visible: comments().length > 0">
                        <div class="count" data-bind="click: showComments">Show <span data-bind="text: commentCount()"></span> <span data-bind="text: commentText"></span></div>
                        <div class="inner-comment-container" data-bind="visible: commentsVisible()==1, foreach: comments">
                            <div class="comment">
                                <div class="left username" data-bind="text: displayName"></div>
                                <time class="right date" data-bind="attr: { 'datetime': date }"></time>
                                <div class="clearfix"></div>
                                <img data-bind="attr: { 'src': userPhoto }" alt="User Profile Image" width="35" height="30"/>
                                <div class="comment_content">
                                       <p data-bind="text: content"></p>
                                </div>
                                <div class="right delete" data-bind="click: $parent.removeComment">Delete?</div>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </section>
                    <textarea class="add_comment expanding" data-bind="expandingTextarea: true, hasfocus: showAddCommentButton, value: newComment"></textarea>
                    <input name="addcomment" type="button" class="submit_button"  value="Post" data-bind="visible: showAddCommentButton()==true || newComment().length > 0, click: addComment"/>
                </article>
                <hr class="article_separator"/>
           </div>
        </script>
        
        <!-- NEW STORY -->
        <script type="text/html" id="new-story-template">
           <div class="profile_section_title" id="new-story">
                <div class="left section_title">New Story</div>
                <div class="right section_button" data-bind="click: $root.cancelNewStory">Cancel</div>
                <div class="clearfix"></div>
           </div>
           <div class="profile_section_content" data-bind="with: newStory">
               <div class="new_story_content">
                   <label>Story:</label>
                   <textarea class="expanding story_edit" data-bind="expandingTextarea: true, value: content" placeholder="What's Your Story?"></textarea>
               </div>
               <input name="add_gallery" type="button" class="submit_button"  value="Add Photos" data-bind="click: $root.showAddGalleryInterface, visible: $root.galleryInterfaceVisible()==0"/>
               <div class="add_photos" data-bind="visible: $root.galleryInterfaceVisible()==1">
                   <div class="upload_container unstyled" data-bind="uploader: true"></div>
               </div>
               <input name="add_story" type="button" class="submit_button" value="Add Story" data-bind="click: $root.addStory"/>
           </div>
        </script>
        
        <!-- CROP PROFILE IMAGE -->
        <script type="text/html" id="crop-profile-image-template">
            <div class="profile_section_title" id="crop-profile-image">
                <div class="left section_title">Please Crop Your Uploaded Image</div>
                <div class="clearfix"></div>
           </div>
           <div class="prifle_section_content" data-bind="with: newProfileImage">
               <div class="full_image">
                   <img data-bind="attr: { 'src': fullSizeImage }, imageCrop: true" style=""  class="upload_fullsize"/>
               </div>
               <div class="thumb_image" style="margin-top: 20px; border: 2px solid red;">
                   <img data-bind="attr: { 'src': fullSizeImage }" style="max-width: 450px;"/>
                   <input type="hidden" id="x1" data-bind="value: xCoord"/>
                   <input type="hidden" id="x2" data-bind="value: x2Coord"/>
                   <input type="hidden" id="y1" data-bind="value: yCoord"/>
                   <input type="hidden" id="y2" data-bind="value: y2Coord"/>
                   <input type="hidden" id="w" data-bind="value: width"/>
                   <input type="hidden" id="h" data-bind="value: height"/>
               </div>
               <input type="button" value="Save Image" data-bind="click: $root.submitImageCrop" class="submit_button" />
           </div>
        </script>
        
        <!-- RESOURCES -->
        <script type="text/html" id="resources-template">
            <div class="profile_section_title" id="myresources">
                <div class="left section_title">My Resources</div>
                <div class="clearfix"></div>
            </div>
            <div class="profile_section_content" data-bind="foreach: resourceTypes">
                <section class="resource_topic" data-bind="visible: resources().length > 0">
                    <div class="resource_topic_header">
                        <div class="resource_topic_name left" data-bind="text: name"></div>
                        <div class="minimize right" data-bind="click: toggleVisibility"><img src="/assets/img/minimize-red.png" alt="Minimise"/></div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="resources" data-bind="foreach: resources, visible: listVisible()==1">
                        <article class="resource">
                            <div class="resource_header">
                                <div class="resource_title left" data-bind="text: name"></div>
                                <div class="resource_options right"><span data-bind="click: $parent.deleteResource">Delete</span></div>
                                <div class="clearfix"></div>    
                            </div>
                            <div class="resource_content">
                                <div class="resource_contact left" data-bind="html: contact"></div>
                                <div class="resource_address right" data-bind="html: address"></div>
                                <div class="clearfix"></div>
                            </div>
                        </article>
                    </div>
                </section>
            </div>
        </script> 
        
        <!-- INLINE SEND MESSAGE MODAL -->
        <div id="send_message" class="new-message" data-bind="with: newMessage" style="display: none">
            <header>
                <h2>New Message</h2>
            </header>
            <div class="fields">
                <span class="fieldname">To:</span> <span data-bind="text: recipients()[0].displayName"></span><br/>
                <span class="fieldname">Subject:</span>
                <input type="text" placeholder="Give this message a subject" id="field_subject" data-bind="value: subject"/>
                <span class="fieldname">Message:</span>
                <textarea data-bind="value: content, expandingTextarea: true" placeholder="Enter your message here"></textarea>
            </div>
            <input type="button" id="button_send" class="submit_button"  value="Send" data-bind="click: $root.sendMessage"/>
        </div>
      
    </div>
</div>  
<div class="clearfix"></div>
<? $this->variablesJS = '<script type="text/javascript">
    var profileImagesUrl="'.$this->profileImagesUrl.'";
    var userGalleryImagesUrl="'.$this->userGalleryImagesUrl.'";
    var userGalleryThumbsUrl="'.$this->userGalleryThumbsUrl.'";
    var townhallBaseUrl="/townhall/";
    var articleBaseUrl="/featured/";
 </script>';
echo $this->variablesJS; ?>
