<? $this->pageTitle = "Registration";
$this->additionalScripts = '<script src="/assets/js/register.js"></script>' ?>

<div id="content">
    <div id="left-column" class="left">
        <div id="logo">
            <img src="/assets/img/logo-home.png" alt="BuzzyGals Logo" />
        </div>
    </div>
    <div id="right-column" class="right" data-bind="loadingWhen: isLoading">
        <div data-bind="template: {name: 'signup-template', if: processState() == 'New' }"></div>
        <div data-bind="template: {name: 'success-template', if: processState() == 'Success' }"></div>
        
        <!-- Templates -->
        
        <!-- REGISTRATION -->
        <script type="text/html" id="signup-template">
            <div id="signup">
                <form id="signup_form" data-bind="with: registration">
                    <h2 class="lightred">Account Credentials</h2>
                    <input type="text" data-bind="value: username" id="field_username" placeholder="Organization E-Mail Address"/>
                    <p class="lightred" data-bind="visible: $root.usernameError().length > 0, text: $root.usernameError"></p>
                    <input type="password" data-bind="value: password" id="field_password" placeholder="Enter Password. Minimum 7 characters"/>
                    <input type="password" data-bind="value: passwordConfirm" id="field_password_confirm" placeholder="Confirm Password"/>
                    <h2 class="lightred">Profile</h2>
                    <input type="text" data-bind="value: fName" id="field_fName" placeholder="Administrator First Name" />
                    <input type="text" data-bind="value: lName" id="field_lName" placeholder="Administrator Last Name" />
                    <input type="text" data-bind="value: displayName" id="field_displayName" placeholder="Organization Name (Shown On Profile)"/>
                    <input type="text" data-bind="value: url" id="field_url" placeholder="Profile URL (buzzygals.com/[yoururl]). No Spaces"/>
                    <h2 class="lightred">Main Location</h2>
                    <label>Country</label><input type="text" class="square" id="field_country" data-bind="autoComplete: $root.countryList, value: countryid, optionsText: 'name', optionsValue: 'id', autoCompleteOptions: {autoFocus: false}, attr : { 'placeholder': 'Country' }"/>
                    <label>State/Province</label><input type="text" class="square" id="field_stateprov"  data-bind="autoComplete: $root.stateList, value: stateprovid, optionsText: 'name', optionsValue: 'id', autoCompleteOptions: {autoFocus: false}"/>
                    <label>City</label><input type="text" class="square" id="field_city"  placeholder="City" data-bind="autoComplete: $root.cityList, value: cityid, optionsText: 'name', optionsValue: 'id', autoCompleteOptions: {autoFocus: false}"/>
                    
                    <input type="hidden" data-bind="initializeValue: usergroup, value: usergroup" id="field_usergroup" value="2"/>
                    <input type="button" class="submit_button" value="Complete Registration" data-bind="click: $root.submitRegistration"/>
                </form>
            </div>
        </script>
        
        <!-- REGISTRATION SUCCESS -->
        <script type="text/html" id="success-template">
            <div class="message">
                <h2>Registration Complete!</h2>
                <p>You have successfully created your account for BuzzyGals. A confirmation e-mail has been sent to the address provided. Please check this message
                    and follow the instructions in order to verify your account. This is necessary before you can access your account.</p>
            </div>
        </script>
        
    </div>
    <div class="clearfix"></div>
</div>
