<body>
    <table width="600" style="border: none; font-size: 13px; font-family: Helvetica, Arial, sans-serif; color: #000; margin: 0; padding: 0">
        <tr cellspacing="0" cellpadding="0" margin="0" padding="0">
            <td width="63"></td>
            <td width="473">
                <img src="http://buzzygals.com/assets/img/logo-home.jpg" alt="BuzzyGals Logo" width="473" height="314"/>
            </td>
            <td width="64"></td>
        </tr>
        <tr height="15"></tr>
        <tr cellspacing="0" cellpadding="0" margin="0" padding="0">
            <table width="600">
                <tr>
                    <td width="600" style="text-align: center">
                    <p>Hello <? echo $this->firstName ?></p>
                    <p>Welcome to BuzzyGals.com. Thank you for registering with us.<br/><br/>
                        All you have to do now is verify your account by clicking the link below, and you may get started. <br/><br/>
                        <a style="color: red;" href="<? echo $this->verificationlink ?>"><? echo $this->verificationlink ?></a><br/><br>
                    </p>
                    <p>If you did not sign up for BuzzyGals, please ignore this message. No further action is required</p>
                    </td>
                </tr>
            </table>
        </tr>
    </table>
</body>