<? $this->pageTitle = "Verification Successful"; ?>
<div id="content">
    <div id="left-column" class="left">
        <div id="logo">
            <img src="/assets/img/logo-home.png" alt="ElleFab Logo" />
        </div>
    </div>
    <div id="right-column" class="right">
        <div class="message">
            <h2>Success!</h2>
            <p>
                Congratulations. Your account has been verified. <br/>
                You may now log in <a href="/login">here</a>.<br/><br/>
                Welcome to BuzzyGals!
            </p>
            <a href="/" title="Login">
                <input type="submit" value="Go To Login Page" name="submit"/>
            </a>
        </div>
    </div>
    <div class="clearfix"></div>
</div>

